project_id = "pjfoiamcflimdreoxvpg"

[functions.ai-gateway]
verify_jwt = false

[functions.recipes]
verify_jwt = false

[functions.recipes-top-up]
verify_jwt = false

[functions.nutrition-lookup]
verify_jwt = false
