import type { Recipe } from "./data";

// Bundled offline recipe catalog — the last-resort guarantee that AI search
// ALWAYS returns something. When the live `recipes` edge function returns nothing
// (both Spoonacular AND TheMealDB down/empty, or the user isn't signed in), the
// app ranks these locally via recommend()/finalizeSearchResults() instead of
// showing the "try different criteria" dead end.
//
// Coverage is deliberate: ~8 vegan, ~7 vegetarian, ~5 pescatarian, ~10 omnivore
// across cuisines and meal types, so the hard safety filter (safeRecipes) always
// leaves several for any realistic diet + allergy profile.
//
// Images are real per-dish photos from TheMealDB's stable media CDN, matched to
// each recipe by dish + diet (no protein/diet conflicts). RecipeImage degrades to
// a placeholder if a URL ever fails, so a recipe is never blocked on its image.

export const bundledRecipes: Recipe[] = [
  // ─── Vegan ───────────────────────────────────────────────────────────────
  {
    id: "bundled-coconut-chickpea-curry",
    title: "Creamy Coconut Chickpea Curry",
    image: "https://www.themealdb.com/images/media/meals/sywrsu1511463066.jpg",
    time: 30, difficulty: "Easy", calories: 420,
    moods: ["Cozy", "Stressed", "Sad"],
    reason: "A warm, soothing one-pot curry — gentle to make on a low-energy night.",
    ingredients: [
      "1 tbsp coconut oil", "1 onion, finely chopped", "3 garlic cloves, minced",
      "1 tbsp grated ginger", "2 tbsp curry powder", "1 can (400g) chickpeas, drained",
      "1 can (400ml) coconut milk", "200g chopped tomatoes", "2 handfuls spinach",
      "Salt and lime, to taste", "Cooked rice, to serve",
    ],
    steps: [
      { text: "Heat the coconut oil in a deep pan over medium heat and soften the onion for 4–5 minutes." },
      { text: "Stir in the garlic, ginger and curry powder and cook for 1 minute until fragrant." },
      { text: "Add the chickpeas, coconut milk and tomatoes. Simmer gently for 12–15 minutes until thickened." },
      { text: "Fold through the spinach until wilted, then season with salt and a squeeze of lime." },
      { text: "Serve over warm rice." },
    ],
    cuisine: "Indian", mealTypes: ["main course", "dinner", "lunch"],
    diets: ["Vegan", "Vegetarian", "High protein"], allergens: [], equipment: [],
    status: "published",
  },
  {
    id: "bundled-tofu-pad-thai",
    title: "Crispy Tofu Pad Thai",
    image: "https://www.themealdb.com/images/media/meals/2wx8cm1763373419.jpg",
    time: 25, difficulty: "Medium", calories: 480,
    moods: ["Adventurous", "Energised", "Happy"],
    reason: "Bright, tangy and full of texture for when you want something lively.",
    ingredients: [
      "200g rice noodles", "200g firm tofu, cubed", "2 tbsp soy sauce",
      "1 tbsp tamarind paste", "1 tbsp maple syrup", "2 garlic cloves, minced",
      "2 spring onions, sliced", "1 handful beansprouts", "2 tbsp crushed peanuts",
      "Lime wedges, to serve",
    ],
    steps: [
      { text: "Soak the rice noodles in hot water until pliable, then drain." },
      { text: "Fry the tofu in a hot oiled pan until golden on all sides, then set aside." },
      { text: "Whisk the soy sauce, tamarind and maple syrup into a sauce." },
      { text: "Stir-fry the garlic, add noodles and sauce, and toss for 2 minutes." },
      { text: "Return the tofu, add beansprouts and spring onions, and toss through." },
      { text: "Top with crushed peanuts and serve with lime." },
    ],
    cuisine: "Thai", mealTypes: ["main course", "dinner"],
    diets: ["Vegan", "Vegetarian"], allergens: ["Peanut", "Soy"], equipment: [],
    status: "published",
  },
  {
    id: "bundled-black-bean-tacos",
    title: "Smoky Black Bean Tacos",
    image: "https://www.themealdb.com/images/media/meals/21yc5s1760524759.jpg",
    time: 20, difficulty: "Easy", calories: 380,
    moods: ["Happy", "Celebratory", "Energised"],
    reason: "Fast, fun and shareable — minimal cooking, maximum flavour.",
    ingredients: [
      "1 can (400g) black beans, drained", "1 tsp smoked paprika", "1 tsp ground cumin",
      "1 garlic clove, minced", "8 small corn tortillas", "1 avocado, sliced",
      "Handful shredded cabbage", "Fresh coriander", "Lime wedges",
    ],
    steps: [
      { text: "Warm the beans with the paprika, cumin and garlic, mashing lightly, for 5 minutes." },
      { text: "Char the tortillas briefly in a dry pan until soft and warm." },
      { text: "Fill each tortilla with beans, avocado and cabbage." },
      { text: "Finish with coriander and a squeeze of lime." },
    ],
    cuisine: "Mexican", mealTypes: ["main course", "dinner", "lunch"],
    diets: ["Vegan", "Vegetarian"], allergens: [], equipment: [],
    status: "published",
  },
  {
    id: "bundled-lemon-quinoa-salad",
    title: "Lemon Herb Quinoa Salad",
    image: "https://www.themealdb.com/images/media/meals/02s6gc1763799560.jpg",
    time: 25, difficulty: "Easy", calories: 350,
    moods: ["Energised", "Focused", "Happy"],
    reason: "Fresh, protein-rich and light — keeps you sharp without weighing you down.",
    ingredients: [
      "150g quinoa", "1 cucumber, diced", "200g cherry tomatoes, halved",
      "1 handful parsley, chopped", "1 handful mint, chopped", "3 tbsp olive oil",
      "Juice of 1 lemon", "Salt and pepper",
    ],
    steps: [
      { text: "Rinse and cook the quinoa in salted water for 12–15 minutes, then drain and cool slightly." },
      { text: "Whisk the olive oil and lemon juice into a dressing." },
      { text: "Toss the quinoa with cucumber, tomatoes and herbs." },
      { text: "Dress, season to taste, and serve." },
    ],
    cuisine: "Mediterranean", mealTypes: ["salad", "main course", "lunch"],
    diets: ["Vegan", "Vegetarian", "High protein"], allergens: [], equipment: [],
    status: "published",
  },
  {
    id: "bundled-hummus-veg-bowl",
    title: "Roasted Vegetable & Hummus Bowl",
    image: "https://www.themealdb.com/images/media/meals/u5e9qq1763795441.jpg",
    time: 35, difficulty: "Easy", calories: 440,
    moods: ["Focused", "Energised", "Cozy"],
    reason: "A balanced, hands-off bowl — roast, assemble, done.",
    ingredients: [
      "1 sweet potato, cubed", "1 courgette, sliced", "1 red pepper, chopped",
      "2 tbsp olive oil", "1 tsp ground cumin", "200g cooked couscous",
      "4 tbsp hummus", "Handful rocket", "Salt and pepper",
    ],
    steps: [
      { text: "Heat the oven to 200°C. Toss the vegetables with oil, cumin and seasoning." },
      { text: "Roast for 25 minutes until tender and caramelised at the edges." },
      { text: "Spoon couscous into bowls and top with the roasted vegetables and rocket." },
      { text: "Add a generous dollop of hummus and serve." },
    ],
    cuisine: "Middle Eastern", mealTypes: ["main course", "dinner", "lunch"],
    diets: ["Vegan", "Vegetarian"], allergens: [], equipment: [],
    status: "published",
  },
  {
    id: "bundled-sesame-noodles",
    title: "Garlicky Sesame Noodles",
    image: "https://www.themealdb.com/images/media/meals/ip5xtp1769779958.jpg",
    time: 15, difficulty: "Easy", calories: 460,
    moods: ["Tired", "Cozy", "Stressed"],
    reason: "Ready in 15 minutes with pantry staples — comfort with zero fuss.",
    ingredients: [
      "200g noodles of choice", "2 tbsp soy sauce", "1 tbsp sesame oil",
      "1 tbsp rice vinegar", "1 tsp maple syrup", "2 garlic cloves, minced",
      "2 spring onions, sliced", "1 tbsp sesame seeds",
    ],
    steps: [
      { text: "Cook the noodles according to the packet, then drain." },
      { text: "Whisk the soy, sesame oil, vinegar, maple and garlic into a sauce." },
      { text: "Toss the warm noodles through the sauce." },
      { text: "Top with spring onions and sesame seeds." },
    ],
    cuisine: "Chinese", mealTypes: ["main course", "dinner"],
    diets: ["Vegan", "Vegetarian"], allergens: ["Soy", "Sesame"], equipment: [],
    status: "published",
  },
  {
    id: "bundled-spiced-lentil-soup",
    title: "Spiced Red Lentil Soup",
    image: "https://www.themealdb.com/images/media/meals/ysqrus1487425681.jpg",
    time: 30, difficulty: "Easy", calories: 320,
    moods: ["Cozy", "Sad", "Stressed"],
    reason: "A hug in a bowl — hearty, warming and naturally high in protein.",
    ingredients: [
      "1 tbsp olive oil", "1 onion, chopped", "2 carrots, diced", "2 garlic cloves, minced",
      "1 tsp ground cumin", "1 tsp turmeric", "200g red lentils", "1 litre vegetable stock",
      "Juice of half a lemon", "Salt and pepper",
    ],
    steps: [
      { text: "Soften the onion and carrots in the oil for 5 minutes." },
      { text: "Stir in the garlic and spices for 1 minute until fragrant." },
      { text: "Add the lentils and stock, then simmer for 20 minutes until soft." },
      { text: "Blend until smooth, brighten with lemon, and season to taste." },
    ],
    cuisine: "Mediterranean", mealTypes: ["soup", "main course", "lunch"],
    diets: ["Vegan", "Vegetarian", "High protein"], allergens: [], equipment: [],
    status: "published",
  },
  {
    id: "bundled-vegan-banana-pancakes",
    title: "Banana Oat Pancakes",
    image: "https://www.themealdb.com/images/media/meals/sywswr1511383814.jpg",
    time: 20, difficulty: "Easy", calories: 300,
    moods: ["Happy", "Energised", "Cozy"],
    reason: "A cheerful, wholesome start — naturally sweet and egg-free.",
    ingredients: [
      "2 ripe bananas", "150g oats", "250ml plant milk", "1 tsp baking powder",
      "1 tsp cinnamon", "1 tsp vanilla", "Oil, for the pan", "Maple syrup, to serve",
    ],
    steps: [
      { text: "Blend the bananas, oats, milk, baking powder, cinnamon and vanilla until smooth." },
      { text: "Rest the batter for 5 minutes to thicken." },
      { text: "Cook spoonfuls in a lightly oiled pan over medium heat until bubbles form, then flip." },
      { text: "Serve warm with maple syrup." },
    ],
    cuisine: "American", mealTypes: ["breakfast"],
    diets: ["Vegan", "Vegetarian"], allergens: [], equipment: [],
    status: "published",
  },

  // ─── Vegetarian (not vegan) ────────────────────────────────────────────────
  {
    id: "bundled-margherita-flatbread",
    title: "Margherita Flatbread",
    image: "https://www.themealdb.com/images/media/meals/x0lk931587671540.jpg",
    time: 20, difficulty: "Easy", calories: 430,
    moods: ["Happy", "Celebratory", "Cozy"],
    reason: "Crisp, cheesy and crowd-pleasing — ready faster than delivery.",
    ingredients: [
      "2 flatbreads or naan", "4 tbsp passata", "1 ball mozzarella, torn",
      "Handful cherry tomatoes, halved", "Fresh basil", "1 tbsp olive oil",
      "Salt and pepper",
    ],
    steps: [
      { text: "Heat the oven to 220°C." },
      { text: "Spread passata over each flatbread and scatter with mozzarella and tomatoes." },
      { text: "Bake for 8–10 minutes until the cheese is bubbling and golden." },
      { text: "Finish with basil, a drizzle of olive oil and seasoning." },
    ],
    cuisine: "Italian", mealTypes: ["main course", "dinner"],
    diets: ["Vegetarian"], allergens: ["Dairy", "Gluten", "Wheat"], equipment: [],
    status: "published",
  },
  {
    id: "bundled-baked-ziti",
    title: "Three-Cheese Baked Ziti",
    image: "https://www.themealdb.com/images/media/meals/wtsvxx1511296896.jpg",
    time: 45, difficulty: "Medium", calories: 560,
    moods: ["Cozy", "Sad", "Celebratory"],
    reason: "Deeply comforting, bubbling pasta bake for when you need a treat.",
    ingredients: [
      "300g ziti or penne", "500g passata", "2 garlic cloves, minced", "1 tsp dried oregano",
      "250g ricotta", "1 ball mozzarella, torn", "40g grated parmesan", "Fresh basil",
      "Salt and pepper",
    ],
    steps: [
      { text: "Heat the oven to 200°C and cook the pasta until just shy of al dente." },
      { text: "Simmer the passata with garlic and oregano for 10 minutes, then season." },
      { text: "Toss the pasta with the sauce and ricotta, then transfer to a baking dish." },
      { text: "Top with mozzarella and parmesan." },
      { text: "Bake for 20 minutes until golden, then scatter with basil." },
    ],
    cuisine: "Italian", mealTypes: ["main course", "dinner"],
    diets: ["Vegetarian"], allergens: ["Dairy", "Gluten", "Wheat"], equipment: [],
    status: "published",
  },
  {
    id: "bundled-halloumi-skewers",
    title: "Halloumi & Vegetable Skewers",
    image: "https://www.themealdb.com/images/media/meals/zub3s91764110535.jpg",
    time: 25, difficulty: "Easy", calories: 410,
    moods: ["Celebratory", "Happy", "Energised"],
    reason: "Golden, salty halloumi with charred veg — festive and easy.",
    ingredients: [
      "250g halloumi, cubed", "1 courgette, thick sliced", "1 red pepper, chunked",
      "1 red onion, wedged", "2 tbsp olive oil", "1 tsp dried oregano",
      "Juice of half a lemon", "Salt and pepper",
    ],
    steps: [
      { text: "Thread the halloumi and vegetables onto skewers." },
      { text: "Brush with olive oil, oregano and seasoning." },
      { text: "Grill or griddle for 3–4 minutes per side until charred and golden." },
      { text: "Finish with a squeeze of lemon." },
    ],
    cuisine: "Mediterranean", mealTypes: ["main course", "dinner"],
    diets: ["Vegetarian"], allergens: ["Dairy"], equipment: [],
    status: "published",
  },
  {
    id: "bundled-mushroom-risotto",
    title: "Mushroom Risotto",
    image: "https://www.themealdb.com/images/media/meals/ssyqwr1511451678.jpg",
    time: 40, difficulty: "Medium", calories: 470,
    moods: ["Cozy", "Focused", "Sad"],
    reason: "Slow, savoury and meditative to stir — a calming cook.",
    ingredients: [
      "1 tbsp olive oil", "1 onion, finely chopped", "250g arborio rice", "300g mushrooms, sliced",
      "1 litre warm vegetable stock", "50ml white wine (optional)", "40g grated parmesan",
      "1 tbsp butter", "Salt and pepper",
    ],
    steps: [
      { text: "Soften the onion in the oil, then add the mushrooms and cook until golden." },
      { text: "Stir in the rice for 1 minute, then add the wine and let it absorb." },
      { text: "Add the stock a ladle at a time, stirring, until the rice is creamy and tender (about 20 minutes)." },
      { text: "Beat in the parmesan and butter, season, and serve." },
    ],
    cuisine: "Italian", mealTypes: ["main course", "dinner"],
    diets: ["Vegetarian"], allergens: ["Dairy"], equipment: [],
    status: "published",
  },
  {
    id: "bundled-spinach-feta-omelette",
    title: "Spinach & Feta Omelette",
    image: "https://www.themealdb.com/images/media/meals/qwtrtp1511799242.jpg",
    time: 12, difficulty: "Easy", calories: 320,
    moods: ["Tired", "Energised", "Focused"],
    reason: "Protein-packed and on the plate in minutes — an easy reset.",
    ingredients: [
      "3 eggs", "2 handfuls spinach", "50g feta, crumbled", "1 tbsp butter",
      "Salt and pepper", "Chives, to serve",
    ],
    steps: [
      { text: "Beat the eggs with a little salt and pepper." },
      { text: "Wilt the spinach in the butter in a non-stick pan." },
      { text: "Pour in the eggs and cook gently, drawing the edges in." },
      { text: "Scatter over the feta, fold, and finish with chives." },
    ],
    cuisine: "Greek", mealTypes: ["breakfast"],
    diets: ["Vegetarian"], allergens: ["Egg", "Dairy"], equipment: [],
    status: "published",
  },
  {
    id: "bundled-paneer-butter-masala",
    title: "Paneer Butter Masala",
    image: "https://www.themealdb.com/images/media/meals/xxpqsy1511452222.jpg",
    time: 35, difficulty: "Medium", calories: 520,
    moods: ["Cozy", "Adventurous", "Celebratory"],
    reason: "Rich, mildly spiced and indulgent — restaurant comfort at home.",
    ingredients: [
      "250g paneer, cubed", "1 tbsp butter", "1 onion, puréed", "2 garlic cloves, minced",
      "1 tbsp grated ginger", "400g chopped tomatoes", "1 tbsp garam masala",
      "100ml cream", "Salt and sugar to taste", "Cooked rice, to serve",
    ],
    steps: [
      { text: "Lightly fry the paneer in the butter until golden, then set aside." },
      { text: "Soften the onion, then add the garlic, ginger and garam masala for 1 minute." },
      { text: "Add the tomatoes and simmer for 12 minutes, then blend smooth." },
      { text: "Stir in the cream and paneer, season with salt and a pinch of sugar, and warm through." },
      { text: "Serve with rice." },
    ],
    cuisine: "Indian", mealTypes: ["main course", "dinner"],
    diets: ["Vegetarian"], allergens: ["Dairy"], equipment: [],
    status: "published",
  },
  {
    id: "bundled-caprese-avocado-toast",
    title: "Caprese Avocado Toast",
    image: "https://www.themealdb.com/images/media/meals/flrajf1762341295.jpg",
    time: 10, difficulty: "Easy", calories: 340,
    moods: ["Energised", "Happy", "Focused"],
    reason: "Fresh, creamy and instant — a bright pick-me-up.",
    ingredients: [
      "2 slices sourdough", "1 avocado", "1 ball mozzarella, sliced",
      "Handful cherry tomatoes, halved", "Fresh basil", "Olive oil", "Salt and pepper",
    ],
    steps: [
      { text: "Toast the sourdough." },
      { text: "Mash the avocado over the toast with a little salt." },
      { text: "Layer over the mozzarella and tomatoes." },
      { text: "Finish with basil, olive oil and pepper." },
    ],
    cuisine: "Italian", mealTypes: ["breakfast", "snack"],
    diets: ["Vegetarian"], allergens: ["Dairy", "Gluten", "Wheat"], equipment: [],
    status: "published",
  },

  // ─── Pescatarian ───────────────────────────────────────────────────────────
  {
    id: "bundled-garlic-butter-salmon",
    title: "Garlic Butter Salmon",
    image: "https://www.themealdb.com/images/media/meals/1548772327.jpg",
    time: 20, difficulty: "Easy", calories: 420,
    moods: ["Focused", "Celebratory", "Cozy"],
    reason: "Quick, elegant and rich in protein — feels special on a weeknight.",
    ingredients: [
      "2 salmon fillets", "2 tbsp butter", "3 garlic cloves, minced", "Juice of half a lemon",
      "Fresh parsley", "Salt and pepper", "Steamed greens, to serve",
    ],
    steps: [
      { text: "Season the salmon and sear skin-side down in a little oil for 4 minutes." },
      { text: "Flip and cook for another 2–3 minutes until just done." },
      { text: "Add the butter and garlic to the pan and spoon over the fish for 1 minute." },
      { text: "Finish with lemon and parsley, and serve with greens." },
    ],
    cuisine: "Mediterranean", mealTypes: ["main course", "dinner"],
    diets: ["Pescatarian", "High protein"], allergens: ["Fish", "Dairy"], equipment: [],
    status: "published",
  },
  {
    id: "bundled-shrimp-linguine",
    title: "Shrimp & Garlic Linguine",
    image: "https://www.themealdb.com/images/media/meals/usywpp1511189717.jpg",
    time: 25, difficulty: "Medium", calories: 510,
    moods: ["Celebratory", "Happy", "Adventurous"],
    reason: "Garlicky, glossy and a little luxurious — date-night easy.",
    ingredients: [
      "250g linguine", "300g raw prawns", "3 garlic cloves, minced", "2 tbsp olive oil",
      "Pinch chilli flakes", "Juice of half a lemon", "Fresh parsley", "Salt and pepper",
    ],
    steps: [
      { text: "Cook the linguine in salted water until al dente, reserving a cup of the water." },
      { text: "Gently fry the garlic and chilli in the oil, then add the prawns and cook until pink." },
      { text: "Toss in the pasta with a splash of the cooking water to make a light sauce." },
      { text: "Finish with lemon, parsley and seasoning." },
    ],
    cuisine: "Italian", mealTypes: ["main course", "dinner"],
    diets: ["Pescatarian"], allergens: ["Shellfish", "Gluten", "Wheat"], equipment: [],
    status: "published",
  },
  {
    id: "bundled-tuna-poke-bowl",
    title: "Tuna Poke Bowl",
    image: "https://www.themealdb.com/images/media/meals/yypwwq1511304979.jpg",
    time: 20, difficulty: "Easy", calories: 450,
    moods: ["Energised", "Adventurous", "Focused"],
    reason: "Cool, fresh and high-protein — no cooking required.",
    ingredients: [
      "200g sushi-grade tuna, cubed", "2 tbsp soy sauce", "1 tsp sesame oil",
      "200g cooked sushi rice", "1 avocado, sliced", "1 cucumber, ribboned",
      "1 carrot, grated", "1 tbsp sesame seeds", "Spring onion, sliced",
    ],
    steps: [
      { text: "Toss the tuna with the soy sauce and sesame oil and chill for 10 minutes." },
      { text: "Divide the rice between bowls." },
      { text: "Arrange the avocado, cucumber and carrot on top." },
      { text: "Add the marinated tuna, then finish with sesame seeds and spring onion." },
    ],
    cuisine: "Japanese", mealTypes: ["main course", "lunch"],
    diets: ["Pescatarian", "High protein"], allergens: ["Fish", "Soy", "Sesame"], equipment: [],
    status: "published",
  },
  {
    id: "bundled-baked-cod",
    title: "Mediterranean Baked Cod",
    image: "https://www.themealdb.com/images/media/meals/1520084413.jpg",
    time: 30, difficulty: "Easy", calories: 360,
    moods: ["Focused", "Cozy", "Sad"],
    reason: "Light, savoury and forgiving — a clean, restorative dinner.",
    ingredients: [
      "2 cod fillets", "200g cherry tomatoes", "2 tbsp olives, pitted", "2 tbsp olive oil",
      "1 garlic clove, sliced", "1 tsp dried oregano", "Juice of half a lemon", "Salt and pepper",
    ],
    steps: [
      { text: "Heat the oven to 200°C." },
      { text: "Scatter the tomatoes, olives and garlic in a baking dish and drizzle with oil." },
      { text: "Nestle in the cod, season, and add the oregano." },
      { text: "Bake for 18–20 minutes until the fish flakes, then finish with lemon." },
    ],
    cuisine: "Mediterranean", mealTypes: ["main course", "dinner"],
    diets: ["Pescatarian", "High protein"], allergens: ["Fish"], equipment: [],
    status: "published",
  },
  {
    id: "bundled-thai-fish-curry",
    title: "Thai Coconut Fish Curry",
    image: "https://www.themealdb.com/images/media/meals/r7mcjm1780261264.jpg",
    time: 30, difficulty: "Medium", calories: 440,
    moods: ["Adventurous", "Cozy", "Celebratory"],
    reason: "Fragrant, creamy and warming — a comforting adventure.",
    ingredients: [
      "400g white fish, cubed", "2 tbsp Thai red curry paste", "1 can (400ml) coconut milk",
      "1 red pepper, sliced", "1 tbsp fish sauce", "1 tsp brown sugar",
      "Juice of 1 lime", "Fresh coriander", "Cooked rice, to serve",
    ],
    steps: [
      { text: "Fry the curry paste in a little oil for 1 minute until fragrant." },
      { text: "Pour in the coconut milk, fish sauce and sugar and bring to a gentle simmer." },
      { text: "Add the pepper and cook for 5 minutes, then add the fish and poach for 5–6 minutes." },
      { text: "Brighten with lime, scatter with coriander, and serve with rice." },
    ],
    cuisine: "Thai", mealTypes: ["main course", "dinner"],
    diets: ["Pescatarian"], allergens: ["Fish"], equipment: [],
    status: "published",
  },

  // ─── Omnivore ────────────────────────────────────────────────────────────
  {
    id: "bundled-lemon-chicken-potatoes",
    title: "One-Pan Lemon Chicken & Potatoes",
    image: "https://www.themealdb.com/images/media/meals/b5ft861583188991.jpg",
    time: 45, difficulty: "Easy", calories: 520,
    moods: ["Cozy", "Focused", "Celebratory"],
    reason: "Everything roasts in one tray — comforting and almost no clean-up.",
    ingredients: [
      "4 chicken thighs", "500g baby potatoes, halved", "2 tbsp olive oil",
      "3 garlic cloves, crushed", "1 lemon, sliced", "1 tsp dried thyme", "Salt and pepper",
    ],
    steps: [
      { text: "Heat the oven to 200°C." },
      { text: "Toss the potatoes with oil, garlic, thyme and seasoning in a roasting tray." },
      { text: "Nestle in the chicken thighs and tuck in the lemon slices." },
      { text: "Roast for 35–40 minutes until the chicken is golden and cooked through." },
    ],
    cuisine: "Mediterranean", mealTypes: ["main course", "dinner"],
    diets: ["High protein"], allergens: [], equipment: [],
    status: "published",
  },
  {
    id: "bundled-honey-garlic-chicken",
    title: "Honey Garlic Chicken Stir-fry",
    image: "https://www.themealdb.com/images/media/meals/wvpsxx1468256321.jpg",
    time: 25, difficulty: "Easy", calories: 480,
    moods: ["Tired", "Energised", "Happy"],
    reason: "Sweet, savoury and fast — a reliable weeknight win.",
    ingredients: [
      "400g chicken breast, sliced", "2 tbsp soy sauce", "2 tbsp honey", "3 garlic cloves, minced",
      "1 tbsp grated ginger", "1 head broccoli, in florets", "1 tbsp oil", "Cooked rice, to serve",
    ],
    steps: [
      { text: "Stir-fry the chicken in the oil over high heat until golden." },
      { text: "Add the garlic and ginger for 30 seconds." },
      { text: "Add the broccoli with a splash of water and cook until just tender." },
      { text: "Stir in the soy and honey and toss until glossy. Serve with rice." },
    ],
    cuisine: "Chinese", mealTypes: ["main course", "dinner"],
    diets: ["High protein"], allergens: ["Soy"], equipment: [],
    status: "published",
  },
  {
    id: "bundled-beef-chili",
    title: "Classic Beef Chili",
    image: "https://www.themealdb.com/images/media/meals/uuqvwu1504629254.jpg",
    time: 45, difficulty: "Easy", calories: 540,
    moods: ["Cozy", "Sad", "Stressed"],
    reason: "A big, warming pot of comfort that only gets better as it sits.",
    ingredients: [
      "500g beef mince", "1 onion, chopped", "2 garlic cloves, minced", "1 tbsp ground cumin",
      "1 tbsp smoked paprika", "1 can (400g) chopped tomatoes", "1 can (400g) kidney beans, drained",
      "1 tbsp tomato purée", "Salt and pepper",
    ],
    steps: [
      { text: "Brown the beef in a large pot, then set aside." },
      { text: "Soften the onion, then add the garlic and spices for 1 minute." },
      { text: "Return the beef, add the tomatoes, beans and purée, and simmer for 30 minutes." },
      { text: "Season to taste and serve." },
    ],
    cuisine: "American", mealTypes: ["main course", "dinner"],
    diets: ["High protein"], allergens: [], equipment: [],
    status: "published",
  },
  {
    id: "bundled-spaghetti-bolognese",
    title: "Spaghetti Bolognese",
    image: "https://www.themealdb.com/images/media/meals/sutysw1468247559.jpg",
    time: 40, difficulty: "Easy", calories: 560,
    moods: ["Cozy", "Happy", "Sad"],
    reason: "The all-rounder comfort dinner everyone reaches for.",
    ingredients: [
      "300g spaghetti", "400g beef mince", "1 onion, chopped", "1 carrot, diced",
      "2 garlic cloves, minced", "500g passata", "1 tbsp tomato purée", "1 tsp dried oregano",
      "Salt and pepper", "Grated parmesan, to serve",
    ],
    steps: [
      { text: "Brown the mince in a large pan, then set aside." },
      { text: "Soften the onion and carrot, then add the garlic for 1 minute." },
      { text: "Return the mince, add the passata, purée and oregano, and simmer for 25 minutes." },
      { text: "Cook the spaghetti, then toss with the sauce and serve with parmesan." },
    ],
    cuisine: "Italian", mealTypes: ["main course", "dinner"],
    diets: [], allergens: ["Gluten", "Wheat", "Dairy"], equipment: [],
    status: "published",
  },
  {
    id: "bundled-korean-beef-bowl",
    title: "Korean Beef Bowl",
    image: "https://www.themealdb.com/images/media/meals/m0p0j81765568742.jpg",
    time: 20, difficulty: "Easy", calories: 500,
    moods: ["Adventurous", "Energised", "Happy"],
    reason: "Sweet-savoury and ready in 20 — a fast flavour hit.",
    ingredients: [
      "400g beef mince", "3 tbsp soy sauce", "1 tbsp brown sugar", "1 tbsp sesame oil",
      "3 garlic cloves, minced", "1 tbsp grated ginger", "2 spring onions, sliced",
      "1 tsp sesame seeds", "Cooked rice, to serve",
    ],
    steps: [
      { text: "Brown the beef in the sesame oil over high heat." },
      { text: "Add the garlic and ginger for 30 seconds." },
      { text: "Stir in the soy and sugar and cook until glossy." },
      { text: "Serve over rice with spring onions and sesame seeds." },
    ],
    cuisine: "Korean", mealTypes: ["main course", "dinner"],
    diets: ["High protein"], allergens: ["Soy", "Sesame"], equipment: [],
    status: "published",
  },
  {
    id: "bundled-pork-fried-rice",
    title: "Pork & Vegetable Fried Rice",
    image: "https://www.themealdb.com/images/media/meals/wympxc1779734808.jpg",
    time: 20, difficulty: "Easy", calories: 470,
    moods: ["Tired", "Happy", "Cozy"],
    reason: "The perfect use for leftover rice — fast, filling and flexible.",
    ingredients: [
      "300g cooked rice, cold", "250g pork mince", "2 eggs, beaten", "1 cup frozen peas and carrots",
      "2 tbsp soy sauce", "2 garlic cloves, minced", "2 spring onions, sliced", "1 tbsp oil",
    ],
    steps: [
      { text: "Brown the pork in the oil over high heat, then push to one side." },
      { text: "Scramble the eggs in the pan, then combine with the pork." },
      { text: "Add the garlic and frozen vegetables and stir-fry for 2 minutes." },
      { text: "Add the rice and soy, toss until hot, and finish with spring onions." },
    ],
    cuisine: "Chinese", mealTypes: ["main course", "dinner", "lunch"],
    diets: [], allergens: ["Egg", "Soy"], equipment: [],
    status: "published",
  },
  {
    id: "bundled-maple-pork-chops",
    title: "Maple Mustard Pork Chops",
    image: "https://www.themealdb.com/images/media/meals/h3ijwo1581013377.jpg",
    time: 25, difficulty: "Easy", calories: 460,
    moods: ["Celebratory", "Focused", "Cozy"],
    reason: "Sticky, savoury-sweet and satisfying with minimal effort.",
    ingredients: [
      "2 pork chops", "2 tbsp maple syrup", "1 tbsp wholegrain mustard", "1 garlic clove, minced",
      "1 tbsp olive oil", "Salt and pepper", "Greens, to serve",
    ],
    steps: [
      { text: "Season the pork chops well." },
      { text: "Sear in the oil for 3–4 minutes per side until golden and cooked through." },
      { text: "Stir the maple, mustard and garlic into the pan and glaze the chops for 1 minute." },
      { text: "Rest briefly and serve with greens." },
    ],
    cuisine: "American", mealTypes: ["main course", "dinner"],
    diets: ["High protein"], allergens: [], equipment: [],
    status: "published",
  },
  {
    id: "bundled-herby-lamb-chops",
    title: "Herby Roast Lamb Chops",
    image: "https://www.themealdb.com/images/media/meals/8xuvhj1763794991.jpg",
    time: 25, difficulty: "Medium", calories: 540,
    moods: ["Celebratory", "Cozy", "Focused"],
    reason: "Tender and herby — a special-occasion main without the fuss.",
    ingredients: [
      "6 lamb chops", "2 tbsp olive oil", "3 garlic cloves, minced", "1 tbsp chopped rosemary",
      "1 tbsp chopped thyme", "Juice of half a lemon", "Salt and pepper",
    ],
    steps: [
      { text: "Rub the chops with oil, garlic, herbs and seasoning and rest for 10 minutes." },
      { text: "Sear in a hot pan for 3 minutes per side for medium." },
      { text: "Rest for 5 minutes, then finish with a squeeze of lemon." },
    ],
    cuisine: "Mediterranean", mealTypes: ["main course", "dinner"],
    diets: ["High protein"], allergens: [], equipment: [],
    status: "published",
  },
  {
    id: "bundled-chicken-tikka-masala",
    title: "Chicken Tikka Masala",
    image: "https://www.themealdb.com/images/media/meals/9ya6o71780262651.jpg",
    time: 40, difficulty: "Medium", calories: 550,
    moods: ["Cozy", "Adventurous", "Celebratory"],
    reason: "Creamy, gently spiced and deeply satisfying — a takeaway favourite.",
    ingredients: [
      "500g chicken breast, cubed", "3 tbsp natural yogurt", "2 tbsp tikka spice blend",
      "1 onion, puréed", "2 garlic cloves, minced", "400g chopped tomatoes", "100ml cream",
      "Fresh coriander", "Cooked rice, to serve",
    ],
    steps: [
      { text: "Marinate the chicken in the yogurt and half the spice for 15 minutes, then sear until browned." },
      { text: "Soften the onion, then add the garlic and remaining spice for 1 minute." },
      { text: "Add the tomatoes and simmer for 10 minutes, then stir in the cream." },
      { text: "Return the chicken and simmer for 8 minutes until cooked. Finish with coriander and serve with rice." },
    ],
    cuisine: "Indian", mealTypes: ["main course", "dinner"],
    diets: [], allergens: ["Dairy"], equipment: [],
    status: "published",
  },
  {
    id: "bundled-turkey-meatballs",
    title: "Turkey & Herb Meatballs",
    image: "https://www.themealdb.com/images/media/meals/8rfd4q1764112993.jpg",
    time: 35, difficulty: "Easy", calories: 430,
    moods: ["Focused", "Energised", "Cozy"],
    reason: "Lean, high-protein and family-friendly in a simple tomato sauce.",
    ingredients: [
      "500g turkey mince", "1 egg", "40g breadcrumbs", "1 tsp dried oregano", "2 garlic cloves, minced",
      "500g passata", "1 tbsp olive oil", "Fresh basil", "Salt and pepper",
    ],
    steps: [
      { text: "Mix the turkey, egg, breadcrumbs, oregano, half the garlic and seasoning, then roll into balls." },
      { text: "Brown the meatballs in the oil, then set aside." },
      { text: "Soften the remaining garlic, add the passata, and simmer for 5 minutes." },
      { text: "Return the meatballs and simmer for 15 minutes until cooked through. Finish with basil." },
    ],
    cuisine: "Italian", mealTypes: ["main course", "dinner"],
    diets: ["High protein"], allergens: ["Egg", "Gluten", "Wheat"], equipment: [],
    status: "published",
  },
];
