import { readStored, writeStored } from "./store";

// Local-pilot simulation of the account + subscription messaging that a
// production build would hand to a backend (Supabase auth email, a payment
// provider's webhook, and a scheduled job for the day-before reminder).
//
// Here we model the same lifecycle honestly with real dates: confirmation
// email on sign-up, a trial-ends-tomorrow reminder scheduled for 24h before
// the trial end, and an automatic charge + emailed receipt when the trial
// lapses without cancellation. `runDue` advances any scheduled item whose
// time has passed, so the behavior is real, just clock-driven on the client.

export type InboxItem = {
  id: string;
  kind: "email" | "push";
  to?: string;                 // recipient for emails
  subject: string;
  body: string;
  createdAt: string;           // ISO — when it was generated/sent
  scheduledFor?: string;       // ISO — set while still pending
  status: "scheduled" | "sent";
  read: boolean;
  tag: "welcome" | "confirm" | "reminder" | "receipt";
};

const INBOX_KEY = "moodfood-inbox";
const DAY = 24 * 60 * 60 * 1000;

export function readInbox(): InboxItem[] { return readStored<InboxItem[]>(INBOX_KEY, []); }
function writeInbox(items: InboxItem[]) { writeStored(INBOX_KEY, items); }

function add(items: InboxItem[], item: Omit<InboxItem, "id" | "read">): InboxItem[] {
  return [{ ...item, id: crypto.randomUUID(), read: false }, ...items].slice(0, 50);
}

export function unreadCount(): number { return readInbox().filter(i => !i.read && i.status === "sent").length; }

export function markAllRead() { writeInbox(readInbox().map(i => ({ ...i, read: true }))); }

// Sent the moment an account is created.
export function sendConfirmationEmail(email: string, name: string) {
  const now = new Date().toISOString();
  let items = readInbox().filter(i => i.tag !== "confirm");
  items = add(items, {
    kind: "email", to: email, tag: "confirm", status: "sent", createdAt: now,
    subject: "Confirm your MoodFood account",
    body: `Hi ${name || "there"}, welcome to MoodFood. Tap the button to confirm ${email} and finish setting up your account.`,
  });
  writeInbox(items);
}

// Sent once the email link is followed.
export function sendWelcomeEmail(email: string, name: string) {
  const now = new Date().toISOString();
  let items = readInbox();
  items = add(items, {
    kind: "email", to: email, tag: "welcome", status: "sent", createdAt: now,
    subject: "You're in. Let's find tonight's dinner.",
    body: `Hi ${name || "there"}, your email is confirmed. MoodFood matches meals to how you feel, your tastes, and your safety needs. Let's get cooking.`,
  });
  writeInbox(items);
}

// Called when the free trial starts. Schedules the day-before reminder; the
// charge + receipt are generated by runDue() when the trial end passes.
export function scheduleTrial(email: string, plan: string, price: string, trialEndsAt: string) {
  const end = new Date(trialEndsAt).getTime();
  const remindAt = new Date(end - DAY).toISOString();
  let items = readInbox().filter(i => i.tag !== "reminder" && i.tag !== "receipt");
  items = add(items, {
    kind: "push", to: email, tag: "reminder", status: "scheduled",
    createdAt: new Date().toISOString(), scheduledFor: remindAt,
    subject: "Your free trial ends tomorrow",
    body: `Heads up — your MoodFood trial ends tomorrow. You'll be charged ${price} for the ${plan} plan unless you cancel before then.`,
  });
  // Stash the pending charge details on a scheduled receipt item.
  items = add(items, {
    kind: "email", to: email, tag: "receipt", status: "scheduled",
    createdAt: new Date().toISOString(), scheduledFor: trialEndsAt,
    subject: `Receipt — MoodFood ${plan} (${price})`,
    body: `Payment received: ${price} for your MoodFood ${plan} subscription. Thanks for cooking with us. Manage or cancel anytime in Settings → Subscription.`,
  });
  writeInbox(items);
}

// Remove scheduled charge/reminder when the user cancels during the trial.
export function cancelScheduled() {
  writeInbox(readInbox().filter(i => i.status !== "scheduled"));
}

// Fire any scheduled item whose time has arrived. Returns true if the trial
// charge fired (so the caller can flip the subscription to "active").
export function runDue(now = Date.now()): { charged: boolean } {
  const items = readInbox();
  let charged = false;
  const next = items.map(i => {
    if (i.status === "scheduled" && i.scheduledFor && new Date(i.scheduledFor).getTime() <= now) {
      if (i.tag === "receipt") charged = true;
      return { ...i, status: "sent" as const, createdAt: new Date(now).toISOString() };
    }
    return i;
  });
  writeInbox(next);
  return { charged };
}

// Demo affordance: jump the clock to the trial end so the full sequence
// (reminder -> charge -> receipt) fires now instead of in 7 days.
export function simulateTrialEnd(): { charged: boolean } {
  const items = readInbox().map(i =>
    i.status === "scheduled" ? { ...i, scheduledFor: new Date(Date.now() - 1000).toISOString() } : i);
  writeInbox(items);
  return runDue();
}
